FROM docker.elastic.co/kibana/kibana:7.3.2 AS custom-kibana
RUN kibana-plugin install https://d3g5vo6xdbdb9a.cloudfront.net/downloads/kibana-plugins/opendistro-alerting/opendistro-alerting-1.3.0.0.zip
